version: '3'
services:
  api:
    restart: always
    #build: .
    image: conduit-api:0
    network_mode: host
    depends_on:
      - postgres
    env_file: .env

  postgres:
    restart: always
    image: postgres:latest
    network_mode: host
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    env_file: .env

volumes:
  db-data:
