addSbtPlugin("org.scalameta"             % "sbt-scalafmt"       % "2.0.2")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat" % "0.1.7")
addSbtPlugin("com.timushev.sbt" % "sbt-updates" % "0.3.4")
addSbtPlugin("net.vonbuchholtz" % "sbt-dependency-check" % "0.2.10")
addSbtPlugin("com.eed3si9n" % "sbt-assembly" % "0.14.9")
addSbtPlugin("au.com.onegeek"            % "sbt-dotenv"         % "2.0.131")
