addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat" % "0.1.4")
addSbtPlugin("com.timushev.sbt" % "sbt-updates" % "0.3.4")
addSbtPlugin("net.vonbuchholtz" % "sbt-dependency-check" % "0.2.10")
addSbtPlugin("org.ensime" % "sbt-ensime" % "2.5.1")
addSbtPlugin("com.eed3si9n" % "sbt-assembly" % "0.14.9")
addCompilerPlugin("org.spire-math" %% "kind-projector" % "0.9.6")
addCompilerPlugin("com.olegpy" %% "better-monadic-for" % "0.3.0-M4")
